### ISSUE TITLE
[Bug]: 在bili视频解析发送期间，会阻塞其他命令

### ISSUE THREAD

**Issue by reine-ishyanami** [zhiyu1998/nonebot-plugin-resolver#17]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

1. 发送一个bilibili url就行视频解析
2. 在解析结果出来后，视频未发送出来前，触发其他指令（貌似只有发送图片的指令会受影响）
3. 会发现bot无法正常响应消息（文本消息似乎可行）

### 预期结果

其他的插件消息应该正常响应，不应该阻塞

### 实际结果

在视频发送期间，图片消息会被阻塞，文本似乎不会

### 截图或视频

[在这里上传图片]

### 插件版本号

使用 git clone 的代码，版本为 `5a533db`
`nonebot2` 版本为 `2.4.0`
`napcat` 版本为 `3.6.5`

### 适配器类型

napcat

### Python版本

Python3.11以上

### 系统

linux

**Comment by zhiyu1998** [comment]
这个可能属于性能上的问题，主要是我的群也达不到你这个并发要求，如果可以你可以PR解决下

**Comment by zhiyu1998** [comment]
下个版本修复这个问题

https://github.com/zhiyu1998/nonebot-plugin-resolver/pull/25
