### ISSUE TITLE
[功能建议]: 可否按需开启某个平台的解析功能

### ISSUE THREAD

**Issue by YipSzeho** [zhiyu1998/nonebot-plugin-resolver#18]
### 你希望看到什么解决方案？

希望可以在.env配置是否关闭某个平台的解析

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by zhiyu1998** [comment]
[下个版本支持](https://github.com/zhiyu1998/nonebot-plugin-resolver/commit/46d26e955d2e8ad1e64464f630a8e1a217afea84)，我先测试一下
