### ISSUE TITLE
配置 IS_OVERSEA似乎无效

### ISSUE THREAD

**Issue by fllesser** [zhiyu1998/nonebot-plugin-resolver#19]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

配置了IS_OVERSEA=True # 是否是海外服务器部署
但是推特的解析，仍然使用了http代理 127.0.0.1:7890，导致报错

### 预期结果

配置了海外服务器部署应该不走http代理

### 实际结果

如图

### 截图或视频

[在这里上传图片]
![Screenshot_20241121_180414_tech lolli toolbox_edit_187815460410402](https://github.com/user-attachments/assets/6600ade7-c83a-461d-b706-6597b4f2dc4a)

### 插件版本号

1.2.2

### 适配器类型

napcat

### Python版本

Python3.9~3.12之间

### 系统

linux

**Comment by zhiyu1998** [comment]
👋 你好！感谢你提交了第一个问题！🔍 你的细心帮助我们发现了新的改进机会，我们会尽快处理。🚀 如果你有更多的想法或疑问，请继续分享，我们非常乐意听取你的声音！🌟 感谢你的支持！

**Comment by fllesser** [comment]
还有就是推特的解析，没有推文，如果是带图片的推，只解析出了第一张图片

**Comment by zhiyu1998** [comment]
> 还有就是推特的解析，没有推文，如果是带图片的推，只解析出了第一张图片

https://developer.x.com/en/portal/products

**Comment by fllesser** [comment]
> > 还有就是推特的解析，没有推文，如果是带图片的推，只解析出了第一张图片
> 
> 
> 
> 但凡了解过的人都不敢说你这话
> 
> 
> 
> https://developer.x.com/en/portal/products
> 
> 

别阴阳怪气的行么，我只是作为用户来阐述我的使用体验而已，用户又不一定看过推的开发者文档

**Comment by zhiyu1998** [comment]
> > > 还有就是推特的解析，没有推文，如果是带图片的推，只解析出了第一张图片
> > 
> > 
> > 但凡了解过的人都不敢说你这话
> > https://developer.x.com/en/portal/products
> 
> 别阴阳怪气的行么，我只是作为用户来阐述我的使用体验而已，用户又不一定看过推的开发者文档

https://www.ithome.com/0/686/929.htm

**Comment by fllesser** [comment]
> > > > 还有就是推特的解析，没有推文，如果是带图片的推，只解析出了第一张图片
> > > 
> > > 
> > > 但凡了解过的人都不敢说你这话
> > > https://developer.x.com/en/portal/products
> > 
> > 别阴阳怪气的行么，我只是作为用户来阐述我的使用体验而已，用户又不一定看过推的开发者文档
> 
> https://www.ithome.com/0/686/929.htm

没了解过，这只是我顺便提的一嘴，重点是配置问题

**Comment by zhiyu1998** [comment]
已修复，下个版本推出
