### ISSUE TITLE
[Bug]: 直接使用nb命令安装的插件似乎还是旧代码

### ISSUE THREAD

**Issue by hakunomiko** [zhiyu1998/nonebot-plugin-resolver#21]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

虚拟环境中查看包版本为1.2.23，但是在config.py与__init__.py中似乎没有全局解析控制的相关代码，在配置文件中添加GLOBAL_RESOLVE_CONTROLLER="bilibili"也无法禁止解析b站链接。直接clone代码后就正常了，是不是发版出问题了。

### 预期结果

能够使用全局解析控制

### 实际结果

无法正常禁止全局解析

### 插件版本号

1.2.23

### 适配器类型

napcat

### Python版本

Python3.11以上

### 系统

windows

**Comment by zhiyu1998** [comment]
这是1.2.24特性啊，测试完成就会提交

> 你可以反馈下测试结果，如果可以下周一发布

![image](https://github.com/user-attachments/assets/df28f234-a571-483d-b80f-e2b354f6c7f9)

https://github.com/zhiyu1998/nonebot-plugin-resolver/issues/18

**Comment by hakunomiko** [comment]
> 这是1.2.24特性啊，测试完成就会提交
> 
> > 你可以反馈下测试结果，如果可以下周一发布
> 
> ![image](https://private-user-images.githubusercontent.com/33365787/389204892-df28f234-a571-483d-b80f-e2b354f6c7f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzM5MTQsIm5iZiI6MTczMjM3MzYxNCwicGF0aCI6Ii8zMzM2NTc4Ny8zODkyMDQ4OTItZGYyOGYyMzQtYTU3MS00ODNkLWI4MGYtZTJiMzU0ZjZjN2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0NTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2FhMjA0ZjZkNDEyMmQwZDEyNGEwZjQ0NDFjYjBiNTEwYzQ2MzUzODdjZmFmYzJlZGQ3NjRmYWYyMTNiMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EyP1kWmA6eZydmhsi7_TMDz74KvDtn1DihFjXzl8UhY)
> 
> #18

原来是这样，感谢回复，我看README的配置项中有这一项还以为已经发了。目前测试下来没有问题，群聊和单聊都能正常阻止解析
