### ISSUE TITLE
[Bug]: 无法下载b站视频

### ISSUE THREAD

**Issue by Rin-aki** [zhiyu1998/nonebot-plugin-resolver#22]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

报错内容与其他issue不同，在群聊中发送b站视频链接报错

### 实际结果

11-24 15:03:39 [INFO] nonebot-plugin-resolver | 正在合并：['/workspaces/mybot/BV1
gsDrYvEKG-res.mp4']                                                              
11-24 15:03:39 [INFO] nonebot-plugin-resolver | {'BV1gsDrYvEKG-video.m4s': 'remov
e', 'BV1gsDrYvEKG-audio.m4s': 'remove'}                                          
11-24 15:03:39 [ERROR] nonebot-plugin-resolver | 解析发送出现错误，具体为        
ActionFailed(status='failed', retcode=200, data=None, echo='3')

### 截图或视频

[在这里上传图片]

### 插件版本号

1.2.20

### 适配器类型

lagrange

### Python版本

Python3.9~3.12之间

### 系统

linux

**Comment by zhiyu1998** [comment]
👋 你好！感谢你提交了第一个问题！🔍 你的细心帮助我们发现了新的改进机会，我们会尽快处理。🚀 如果你有更多的想法或疑问，请继续分享，我们非常乐意听取你的声音！🌟 感谢你的支持！

**Comment by Rin-aki** [comment]
补充一下：在docker内部运行Python3.9-slim，已经安装ffmpeg

**Comment by Rin-aki** [comment]
![image](https://github.com/user-attachments/assets/597f975d-f3ed-46a8-abbf-2c1dc1b05ea8)

**Comment by Rin-aki** [comment]
找到原因了，lagrange没添加对应的目录

**Comment by Pochinki98** [comment]
@Asukaaa648 请教一下如何解决的？
