### ISSUE TITLE
[Bug]: b站视频尚未下载完毕就已经发送

### ISSUE THREAD

**Issue by Rin-aki** [zhiyu1998/nonebot-plugin-resolver#23]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

发送一个bilibili url就行视频解析
在解析结果出来后，视频未发送出来前就已经发送出来。

### 实际结果

qq中显示视频已过期

### 截图或视频

[在这里上传图片]

### 插件版本号

1.2.20

### 适配器类型

lagrange

### Python版本

Python3.9~3.12之间

### 系统

linux

**Comment by Rin-aki** [comment]
貌似不是尚未下载完毕，视频确实已经下载，但是lagrange好像未能正确发送视频，
![image](https://github.com/user-attachments/assets/fbc89474-b2ee-430b-b77b-b8364633f09e)
路径中的视频是正常的，可播放
![image](https://github.com/user-attachments/assets/8c39e494-dfc9-4227-8f52-26ee7c60e119)

**Comment by zhiyu1998** [comment]
lagrange 不是最新版本都支持发视频了吗，怎么还出现之前的状况？

为了验证你的说法我去下了一下lagrange：

1. 下载
> https://github.com/LagrangeDev/Lagrange.Core/releases/tag/nightly

2. 启动
![image](https://github.com/user-attachments/assets/dd36734e-2234-473d-99cf-40670b821a8e)

3. 发送哔哩哔哩验证

![image](https://github.com/user-attachments/assets/859317ec-aa7f-42e9-8dbe-5cb9dbbc4168)

4. 验证失败

结论：复现不出你的问题，我换 lagrange 都是正常发送，`建议你实在不行换 napcat 试试其他协议`
