### ISSUE TITLE
求助 启动时出错

### ISSUE THREAD

**Issue by xANoyU** [zhiyu1998/nonebot-plugin-resolver#30]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

nb plugin install nonebot-plugin-resolver 安装插件
下载项目插件文件夹到Bot插件文件夹
启动

### 实际结果

[123.log](https://github.com/user-attachments/files/18026350/123.log)

### 插件版本号

nonebot-plugin-resolver-master

### 适配器类型

LLOneBot

### Python版本

Python3.11以上

### 系统

windows

**Comment by zhiyu1998** [comment]
这个是不是你在你的 miniconda 安装 `nonebot_plugin_htmlrender` 的问题，好像没看到 `nonebot-plugin-resolver`

**Comment by xANoyU** [comment]
已解决 是zhenxunBot的问题, 只能另外开个Bot使用此插件
