### ISSUE TITLE
[Bug]: 油管视频下载失败

### ISSUE THREAD

**Issue by tamakyi** [zhiyu1998/nonebot-plugin-resolver#7]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

08-07 22:41:19 [SUCCESS] nonebot | OneBot V11 ********* | [message.group.normal]: Message -2147454493 from ******@[群:******] 'https://www.youtube.com/watch?v=VpOBAxwzjB4'
08-07 22:41:19 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-resolver, lineno=68)
08-07 22:41:27 [SUCCESS] nonebot | OneBot V11 ********* | [message_sent]: {'time': 1723041687, 'self_id': ******, 'post_type': 'message_sent', 'user_id': *********, 'message_id': -2147454491, 'real_id': -2147454491, 'message_seq': -2147454491, 'message_type': 'group', 'sender': {'user_id': ******, 'nickname': '宇宙级CQCQ', 'card': '', 'role': 'member'}, 'raw_message': '视频解析插件识别：油管，ラビットホール-DECO*27/Covered by 雪月りあ', 'font': 14, 'sub_type': 'normal', 'message': '视频解析插件识别：油管，ラビットホール-DECO*27/Covered by 雪月りあ\n', 'message_format': 'string', 'group_id': ******, 'target_id': ******}
08-07 22:41:38 [ERROR] nonebot-plugin-resolver | 下载出现错误，具体为
ActionFailed(status='failed', retcode=1200, data=None, message='文件root/momoko/Momoko/temp.mp4异常，不存在', wording='文件root/momoko/Momoko/temp.mp4异常，不存在', echo='9')

### 预期结果

正常解析下载视频

### 实际结果

08-07 22:41:38 [ERROR] nonebot-plugin-resolver | 下载出现错误，具体为
ActionFailed(status='failed', retcode=1200, data=None, message='文件root/momoko/Momoko/temp.mp4异常，不存在', wording='文件root/momoko/Momoko/temp.mp4异常，不存在', echo='9')

### 截图或视频

[在这里上传图片]

### 版本

1.7.1 (默认)

**Comment by zhiyu1998** [comment]
油管这个需要综合分析：
1. 首先如果是`海外要开启IS_OVERSEA`
2. 不是的话挂梯子要看下`端口是否在7890`，不是的话改一下，另外梯子不行也要`多换节点`尝试
3. 验证下 `yt-dlp` 当前版本是否可以下载

**Comment by tamakyi** [comment]
> 油管这个需要综合分析：
> 1. 首先如果是`海外要开启IS_OVERSEA`
> 2. 不是的话挂梯子要看下`端口是否在7890`，不是的话改一下，另外梯子不行也要`多换节点`尝试
> 3. 验证下 `yt-dlp` 当前版本是否可以下载

我的服务器在hk，所以配置文件是这样写的:
'''                                         IS_OVERSEA=True # 是否是海外服务器部署                                              IS_LAGRANGE=False # 是否是拉格朗日（https://github.com/KonataDev/Lagrange.Core）    
#RESOLVER_PROXY = "http://127.0.0.1:7890" # 代理                                    R_GLOBAL_NICKNAME = "视频解析插件"
'''

然后检查了yt模块也是正常的:
'''
# yt-dlp https://www.youtube.com/watch?v=VpOBAxwzjB4
[youtube] Extracting URL: https://www.youtube.com/watch?v=VpOBAxwzjB4
[youtube] VpOBAxwzjB4: Downloading webpage
[youtube] VpOBAxwzjB4: Downloading ios player API JSON
[youtube] VpOBAxwzjB4: Downloading web creator player API JSON
[youtube] VpOBAxwzjB4: Downloading m3u8 information
[info] VpOBAxwzjB4: Downloading 1 format(s): 137+251
[download] Destination: ラビットホール-DECO＊27⧸Covered by 雪月りあ [VpOBAxwzjB4].f137.mp4
[download] 100% of   31.59MiB in 00:00:29 at 1.06MiB/s
[download] Destination: ラビットホール-DECO＊27⧸Covered by 雪月りあ [VpOBAxwzjB4].f251.webm
[download] 100% of    1.07MiB in 00:00:01 at 993.88KiB/s
[Merger] Merging formats into "ラビットホール-DECO＊27⧸Covered by 雪月りあ [VpOBAxwzjB4].mkv"
Deleting original file ラビットホール-DECO＊27⧸Covered by 雪月りあ [VpOBAxwzjB4].f137.mp4 (pass -k to keep)
Deleting original file ラビットホール-DECO＊27⧸Covered by 雪月りあ [VpOBAxwzjB4].f251.webm (pass -k to keep)
'''

**Comment by zhiyu1998** [comment]
我已经尝试修复，你可以有时间使用最快的 `pip` 安装体验看看是否还存在问题

升级到 `v1.1.17`
